#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 17 22:03:24 2018

@author: maurice
"""
import numpy as np

# converte a saída para array com K unidades

Y_dict = {0.0: np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
          1.0: np.array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0]),
          2.0: np.array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
          3.0: np.array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
          4.0: np.array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
          5.0: np.array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
          6.0: np.array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
          7.0: np.array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
          8.0: np.array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
          9.0: np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])}


# algoritmo-de-gradiente_tamanho-camada-oculta_taxa-de-aprendizado
# no MBGD (Mini Batch GD) há também o tamanho do batch no final

params = {"GD_25_0.5":{"hidden_layer_sizes":(25,), "activation": 'logistic', "solver": 'sgd', 
                       "alpha" : 0, "batch_size" : 5000, "learning_rate" : 'constant',
                       "learning_rate_init": 0.5, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                       "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                       "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                       "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "GD_50_0.5":{"hidden_layer_sizes":(50,), "activation": 'logistic', "solver": 'sgd', 
                       "alpha" : 0, "batch_size" : 5000, "learning_rate" : 'constant',
                       "learning_rate_init": 0.5, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                       "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                       "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                       "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "GD_100_0.5":{"hidden_layer_sizes":(100,), "activation": 'logistic', "solver": 'sgd', 
                       "alpha" : 0, "batch_size" : 5000, "learning_rate" : 'constant',
                       "learning_rate_init": 0.5, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                       "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                       "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                       "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "GD_25_1":{"hidden_layer_sizes":(25, ), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 5000, "learning_rate" : 'constant',
                      "learning_rate_init": 1, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "GD_50_1":{"hidden_layer_sizes":(50, ), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 5000, "learning_rate" : 'constant',
                      "learning_rate_init": 1, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "GD_100_1":{"hidden_layer_sizes":(100, ), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 5000, "learning_rate" : 'constant',
                      "learning_rate_init": 1, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "GD_25_10":{"hidden_layer_sizes":(25,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 5000, "learning_rate" : 'constant',
                      "learning_rate_init": 10, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "GD_50_10":{"hidden_layer_sizes":(50,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 5000, "learning_rate" : 'constant',
                      "learning_rate_init": 10, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "GD_100_10":{"hidden_layer_sizes":(100,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 5000, "learning_rate" : 'constant',
                      "learning_rate_init": 10, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "SGD_25_0.5":{"hidden_layer_sizes":(25,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 1, "learning_rate" : 'constant',
                      "learning_rate_init": 0.5, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "SGD_50_0.5":{"hidden_layer_sizes":(50,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 1, "learning_rate" : 'constant',
                      "learning_rate_init": 0.5, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "SGD_100_0.5":{"hidden_layer_sizes":(100,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 1, "learning_rate" : 'constant',
                      "learning_rate_init": 0.5, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "SGD_25_1":{"hidden_layer_sizes":(25,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 1, "learning_rate" : 'constant',
                      "learning_rate_init": 1, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "SGD_50_1":{"hidden_layer_sizes":(50,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 1, "learning_rate" : 'constant',
                      "learning_rate_init": 1, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "SGD_100_1":{"hidden_layer_sizes":(100,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 1, "learning_rate" : 'constant',
                      "learning_rate_init": 1, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "SGD_25_10":{"hidden_layer_sizes":(25,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 1, "learning_rate" : 'constant',
                      "learning_rate_init": 10, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "SGD_50_10":{"hidden_layer_sizes":(50,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 1, "learning_rate" : 'constant',
                      "learning_rate_init": 10, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "SGD_100_10":{"hidden_layer_sizes":(100,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 1, "learning_rate" : 'constant',
                      "learning_rate_init": 10, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_25_0.5_10":{"hidden_layer_sizes":(25,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 10, "learning_rate" : 'constant',
                      "learning_rate_init": 0.5, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_50_0.5_10":{"hidden_layer_sizes":(50,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 10, "learning_rate" : 'constant',
                      "learning_rate_init": 0.5, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_100_0.5_10":{"hidden_layer_sizes":(100,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 10, "learning_rate" : 'constant',
                      "learning_rate_init": 0.5, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_25_1_10":{"hidden_layer_sizes":(25,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 10, "learning_rate" : 'constant',
                      "learning_rate_init": 1, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_50_1_10":{"hidden_layer_sizes":(50,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 10, "learning_rate" : 'constant',
                      "learning_rate_init": 1, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_100_1_10":{"hidden_layer_sizes":(100,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 10, "learning_rate" : 'constant',
                      "learning_rate_init": 1, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_25_10_10":{"hidden_layer_sizes":(25,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 10, "learning_rate" : 'constant',
                      "learning_rate_init": 10, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_50_10_10":{"hidden_layer_sizes":(50,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 10, "learning_rate" : 'constant',
                      "learning_rate_init": 10, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_100_10_10":{"hidden_layer_sizes":(100,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 10, "learning_rate" : 'constant',
                      "learning_rate_init": 10, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_25_0.5_50":{"hidden_layer_sizes":(25,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 50, "learning_rate" : 'constant',
                      "learning_rate_init": 0.5, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_50_0.5_50":{"hidden_layer_sizes":(50,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 50, "learning_rate" : 'constant',
                      "learning_rate_init": 0.5, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_100_0.5_50":{"hidden_layer_sizes":(100,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 50, "learning_rate" : 'constant',
                      "learning_rate_init": 0.5, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_25_1_50":{"hidden_layer_sizes":(25,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 50, "learning_rate" : 'constant',
                      "learning_rate_init": 1, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_50_1_50":{"hidden_layer_sizes":(50,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 50, "learning_rate" : 'constant',
                      "learning_rate_init": 1, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_100_1_50":{"hidden_layer_sizes":(100,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 50, "learning_rate" : 'constant',
                      "learning_rate_init": 1, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_25_10_50":{"hidden_layer_sizes":(25,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 50, "learning_rate" : 'constant',
                      "learning_rate_init": 10, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_50_10_50":{"hidden_layer_sizes":(50,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 50, "learning_rate" : 'constant',
                      "learning_rate_init": 10, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          "MBGD_100_10_50":{"hidden_layer_sizes":(100,), "activation": 'logistic', "solver": 'sgd', 
                      "alpha" : 0, "batch_size" : 50, "learning_rate" : 'constant',
                      "learning_rate_init": 10, "power_t": 0.5, "max_iter": 10000, "shuffle" : False, 
                      "random_state" : None, "tol": 0.0001, "verbose": False, "warm_start" : False,
                      "momentum":0, "nesterovs_momentum" : False, "early_stopping" : False,
                      "validation_fraction": 0.1, "beta_1":0.9, "beta_2": 0.999, "epsilon":1e-08},
          }

#from sklearn.model_selection import train_test_split
#from sklearn.metrics import classification_report, confusion_matrix

#X_train, X_test, Y_train, Y_test : train_test_split(X, Y, test_size : 0.25, random_state : 10)
#X_train, X_val, Y_train, Y_val
#ann.score(X_test, [Y_dict[y] for y in Y_test])
#yy : np.array([Y_dict[y] for y in Y_test])
#print(confusion_matrix(yy ,predictions))  : train_test_split(X_train, Y_train, test_size : 0.20, random_state : 10)

# 784, 50, 10, 1
          
#hidden_layer_sizes : (25,), solver:'sgd', max_iter : 100000,
#                        batch_size : 20, tol : 0.0001, 
#                        learning_rate:'constant', learning_rate_init:0.5,
#                        activation : 'logistic', random_state : 0
          
          #Y_dict : {0.0: np.array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]),
#          1.0: np.array([0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]),
#          2.0: np.array([0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]),
#          3.0: np.array([0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]),
#          4.0: np.array([0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]),
#          5.0: np.array([0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]),
#          6.0: np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]),
#          7.0: np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]),
#          8.0: np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]),
#          9.0: np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0])}
